### ISSUE TITLE
[ISSUE] Crypt_GPG is run as the web user, and the web user has no home directory

### ISSUE THREAD

**Issue by vzool** [paragonie/gpg-mailer#3]
Hi,

When I try to encrypt a message while I'm **logged as a Server Admin** the encrypted message is generated with no problem at all, But while I let the **Web Server** to do the work on behave of me an **Exception** will be thrown:

```
The 'homedir' \"\/var\/www\/.gnupg\" is not readable or does not exist and cannot be created. This can 
happen if 'homedir' is not specified in the Crypt_GPG options, Crypt_GPG is run as the web user, and the web user has no home directory.
```

How can I make a `homedir` for a web user `www-data`?
Is it necessary or there is something else here? 

Thanks

**Comment by vzool** [comment]
I found some solution [here](https://serverfault.com/questions/501583/how-do-i-change-www-data-home-directory-from-var-www-to-home-www-data). But, it couldn't work.

Because, while I tried this:

```shell
➜ admin@dev sudo usermod -d /home/admin/AppWeb/keyring www-data
```

An Error thrown: `usermod: user www-data is currently used by process 10728`

So, I managed to shut down `apache` service, do the changes and then start `apache` again, like this:

```
➜ admin@dev sudo service apache2 stop
➜ admin@dev sudo usermod -d /home/admin/AppWeb/keyring www-data # set home directory
➜ admin@dev sudo service apache2 start
```

After that, error still the same.
Even I tried to give the `keyring` directory this permission: `chown admin:www-data keyring -R`

But, when I set this permission `chown www-data:www-data keyring -R`.
Anything worked as expected. Do I did something wrong here?

Thanks

**Comment by paragonie-scott** [comment]
The "fun" thing here is that you don't have to use a true homedir for GPG keyrings to work.

```terminal
mkdir /var/www/outside-webroot
chown -R phpuser:phpuser /var/www/outside-webroot
```

And then:

```php
<?php
use ParagonIE\GPGMailer\GPGMailer;
use Zend\Mail\Message;
use Zend\Mail\Transport\Sendmail;

$message = new Message;
$message->addTo('test@example.com', 'Test Email');
$message->setBody('Cleartext for now. Do not worry; this gets encrypted.');

$gpgMailer = new GPGMailer(
    new Sendmail(), 
    ['homedir' => '/var/www/outside-webroot']
);
```

**Comment by paragonie-scott** [comment]
Related, but off-topic: Are you aware of [Discretion](https://github.com/paragonie/discretion)? We're building GPG-Mailer into a self-hostable microservice, though we also plan on running one ourselves. If you'd find something like that useful, I can dedicate some time to push that past the finish line once I've wrapped up this week's work.

**Comment by rugk** [comment]
So is this the way you suggest it to be used?

Because I guess it is pretty common in webserver scenarios that the user has no home dir. So you may:
* add it to the doc, somewhere/somehow
* or change the program logic, so it uses some "clever value" by default or similar.

**Comment by paragonie-scott** [comment]
I'm not sure how to do that in a way that won't lead to someone dropping their GPG keyring into `public_html`.

**Comment by rugk** [comment]
Hmm okay, yeah, then maybe just document it?

**Comment by vzool** [comment]
> The "fun" thing here is that you don't have to use a true homedir for GPG keyrings to work.
> 
> mkdir /var/www/outside-webroot
> chown -R phpuser:phpuser /var/www/outside-webroot
> And then:
> 
> <?php
> use ParagonIE\GPGMailer\GPGMailer;
> use Zend\Mail\Message;
> use Zend\Mail\Transport\Sendmail;
> 
> $message = new Message;
> $message->addTo('test@example.com', 'Test Email');
> $message->setBody('Cleartext for now. Do not worry; this gets encrypted.');
> 
> $gpgMailer = new GPGMailer(
>     new Sendmail(), 
>     ['homedir' => '/var/www/outside-webroot']
> );

Looks cool, but I tried and it does returned the old Exception again.
So, I restored it to a woking one for me, which is without specifying `homedir` in the constructor of `GPGMailer`.

### That's Fantastic!!!

<img width="1138" alt="screen shot 2018-07-02 at 11 22 39 pm" src="https://user-images.githubusercontent.com/4952736/42184904-c44994f0-7e4f-11e8-9252-e34005c431c2.png">

Now our **Android Bug Reports** will be sent encrypted, because our report is "Full Report" to fix harder problems.

Thank you so much <3

**Comment by rugk** [comment]
Okay, you already mention it in the examples, but as you may see, not everyone notices or so… :thinking: 

Actually I could imagine this thing here to be documented in "FAQ-style" quite good.

**Comment by paragonie-scott** [comment]
Yeah, improving the documentation is a damned good idea. :)

**Comment by vzool** [comment]
> Related, but off-topic: Are you aware of Discretion? We're building GPG-Mailer into a self-hostable microservice, though we also plan on running one ourselves. If you'd find something like that useful, I can dedicate some time to push that past the finish line once I've wrapped up this week's work.

I will give it a shot ^_^
